
import Layout from "@features/Layouts";
import { DarkModeProvider, MuiCustomTheme } from "@features/Theme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DarkModeProvider>
          <MuiCustomTheme>
            <Layout>{children}</Layout>
          </MuiCustomTheme>
        </DarkModeProvider>
      </body>
    </html>
  );
}
